### ISSUE TITLE
[7월 20일] 캠퍼스픽 Backend 회의

### ISSUE THREAD

**Issue by dnwlsrla40** [PickFullStack/Back#2]
# 7월 20일 캠퍼스픽 Backend 회의

## 1. git branch 관련

master, dev, hotpics branch 사용

## 2. issue,milestone 관련

milestone과 issue 사용하기로 결정.

**Label**
 - bug : 개발 목록에 대한 테스트 진행 및 bug 내용작성
 - development : 개발을 하기 위해 사전에 완료되어야 하는 task 목록
 - documentation : 팀과 소통하기위한 문서 작업
 - meeting : 미팅에 필요한 내용/ 확인 사항 등을 정리
 - todo : 각자 해야 할 task를 등록

## 3. 태그 사용에 관한 의견 수립

  1) 설명 빼고 진행하는 방식
  2) default로 사이트에서 6개 정도 제공, 후에 사용자가 등록할 수 있는 방식으로 진행

        이 기능이 중요한 기능 같아 보이진 않아 우선 1안 으로 결정하여 개발 진행 후에 추가 고려

## 4. 포스팅 목록 API에 수정일자 추가

DB에 updated_at으로 등록, 형식은 Spring boot에서 시,분,초 형식으로 가공 후 제공

## 5. Mongodb db Mapping 이름 방식

Camelcase or snake_case 방식

DB : snake_case 방식  
Spring : camelCase 방식

## 6. SpringBoot에서 MongoDB에 접근해 사용하는 방식

 - MongoRepository<T,ID> 방식
 - MongoTemplate 빈 방식

아직 정확하진 않지만 후에 기능들을 위해서 MongoTemplate 빈을 Customize해서 사용하는 방식으로 진행

## 7. 문서에 관하여

Requirement Document, 기능 정의서, API 명세서 등 document 작성에 관하여 공지

## 8. logging에 관하여

log4jUnit이 기본으로 사용 + 그 외 spring boot log tool에 대해서 알아보기

## 9. Back 더미 데이터

포스팅 목록 API 관련 서버 DB에 맞춘 더미데이터가 필요

- context: md파일  

## 10. 7월 31일까지 정확한 구현 기능들 정리 필요

**Comment by Minsoo-web** [comment]
md 문서가 너무 깔끔해서 보기 좋습니다. 
이런 회의 목록들은 issue 로 남기기 보다는 Docs 폴더에 back/meetings/ 로 남겨주시면 나중에 보기 더 편할 것 같습니다. 👍

**Comment by dnwlsrla40** [comment]
네 참고하여 올려놓았습니다
